name: multigyan_sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Personal Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Official Repo
        env:
          OFFICIAL_TOKEN: ${{ secrets.OFFICIAL_GIT_TOKEN }}
        run: |
          # Configure git with the token
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Add remote with token embedded in URL
          git remote add official_repo https://oauth2:${OFFICIAL_TOKEN}@github.com/Multigyan/multigyan.git
          
          # Push to official repo
          git push official_repo main --force --set-upstream
